#!/bin/sh
#/ Usage: test
#/
#/ Bootstrap and run all tests.
#/

set -e
cd $(dirname "$0")/..

[ "$1" = "--help" -o "$1" = "-h" -o "$1" = "help" ] && {
    grep '^#/' <"$0"| cut -c4-
    exit 0
}

export RAILS_VERSION=3.2.21
script/bootstrap || bundle update
bundle exec rake

export RAILS_VERSION=4.2.5
script/bootstrap || bundle update
bundle exec rake
